// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package queue.actions;

import java.util.concurrent.ScheduledFuture;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import queue.proxies.ENU_JobStatus;
import queue.repositories.JobRepository;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserException;

public class CancelJob extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __job;
	private queue.proxies.Job job;
	private java.lang.Boolean removeWhenRunning;

	public CancelJob(IContext context, IMendixObject job, java.lang.Boolean removeWhenRunning)
	{
		super(context);
		this.__job = job;
		this.removeWhenRunning = removeWhenRunning;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.job = __job == null ? null : queue.proxies.Job.initialize(getContext(), __job);

		// BEGIN USER CODE
		JobRepository jobRepository = new JobRepository();
		ScheduledFuture<?> future; 
		try {
			future = jobRepository.get(job.getMendixObject());
		} catch (UserException e) {
			return false;
		}
		
		boolean cancelled = future.cancel(removeWhenRunning);
		
		if(cancelled) {
			job.setStatus(ENU_JobStatus.Cancelled);
			job.commit();
		}
		
		return cancelled;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CancelJob";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
