// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package queue.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import queue.helpers.JobCanceller;
import queue.repositories.ScheduledJobRepository;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CancelJob extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __job;
	private queue.proxies.Job job;
	private java.lang.Boolean removeWhenRunning;

	public CancelJob(IContext context, IMendixObject job, java.lang.Boolean removeWhenRunning)
	{
		super(context);
		this.__job = job;
		this.removeWhenRunning = removeWhenRunning;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.job = __job == null ? null : queue.proxies.Job.initialize(getContext(), __job);

		// BEGIN USER CODE
		ScheduledJobRepository jobRepository = ScheduledJobRepository.getInstance();
		JobCanceller jobCanceller = new JobCanceller();
		jobCanceller.cancel(this.context(), jobRepository, job, removeWhenRunning);
		FeedbackHelper.addRefreshClass(this.context(), "Queue.Job");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CancelJob";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
